import assert from 'assert';

import { parseStack } from '../../main/util/index.js';

describe('parseStack', () => {

    it('parses error stack generated by compiler', () => {
        const stack = `
          error: Error [BoomError]: Something happened, but we don't know what
        at compute (ns:endpoint:eXphQV7F0W7bq6YL:latest:3:340)
        at ns:SSi8wguqb64m76RE:root:9uJNBoCS (ns:endpoint:eXphQV7F0W7bq6YL:latest:3:609)
        at ns:SSi8wguqb64m76RE:root:result (ns:endpoint:eXphQV7F0W7bq6YL:latest:3:480)
        at ns:eXphQV7F0W7bq6YL:root:Hvok7Y1K:Q8niRNV4 (ns:endpoint:eXphQV7F0W7bq6YL:latest:3:1358)
        at ns:eXphQV7F0W7bq6YL:root:Hvok7Y1K:result (ns:endpoint:eXphQV7F0W7bq6YL:latest:3:1220)
        at ns:endpoint:eXphQV7F0W7bq6YL:latest:3:1070
        at compute (ns:endpoint:eXphQV7F0W7bq6YL:latest:3:209)
        at ns:eXphQV7F0W7bq6YL:root:Hvok7Y1K (ns:endpoint:eXphQV7F0W7bq6YL:latest:3:1048)
        at async Promise.all (index 0)
        at async ns:eXphQV7F0W7bq6YL:root:result (ns:endpoint:eXphQV7F0W7bq6YL:latest:3:852)
        `;
        const parsed = parseStack(stack);
        assert.deepStrictEqual(parsed, [
            {
                symbol: 'compute',
                source: 'ns:endpoint:eXphQV7F0W7bq6YL:latest:3:340',
                graphId: undefined,
                nodeUid: undefined,
            },
            {
                symbol: 'ns:SSi8wguqb64m76RE:root:9uJNBoCS',
                source: 'ns:endpoint:eXphQV7F0W7bq6YL:latest:3:609',
                graphId: 'SSi8wguqb64m76RE',
                nodeUid: 'root:9uJNBoCS',
            },
            {
                symbol: 'ns:SSi8wguqb64m76RE:root:result',
                source: 'ns:endpoint:eXphQV7F0W7bq6YL:latest:3:480',
                graphId: 'SSi8wguqb64m76RE',
                nodeUid: 'root:result',
            },
            {
                symbol: 'ns:eXphQV7F0W7bq6YL:root:Hvok7Y1K:Q8niRNV4',
                source: 'ns:endpoint:eXphQV7F0W7bq6YL:latest:3:1358',
                graphId: 'eXphQV7F0W7bq6YL',
                nodeUid: 'root:Hvok7Y1K:Q8niRNV4',
            },
            {
                symbol: 'ns:eXphQV7F0W7bq6YL:root:Hvok7Y1K:result',
                source: 'ns:endpoint:eXphQV7F0W7bq6YL:latest:3:1220',
                graphId: 'eXphQV7F0W7bq6YL',
                nodeUid: 'root:Hvok7Y1K:result',
            },
            {
                symbol: 'compute',
                source: 'ns:endpoint:eXphQV7F0W7bq6YL:latest:3:209',
                graphId: undefined,
                nodeUid: undefined,
            },
            {
                symbol: 'ns:eXphQV7F0W7bq6YL:root:Hvok7Y1K',
                source: 'ns:endpoint:eXphQV7F0W7bq6YL:latest:3:1048',
                graphId: 'eXphQV7F0W7bq6YL',
                nodeUid: 'root:Hvok7Y1K',
            },
            {
                symbol: 'Promise.all',
                source: 'index 0',
                graphId: undefined,
                nodeUid: undefined,
            },
            {
                symbol: 'ns:eXphQV7F0W7bq6YL:root:result',
                source: 'ns:endpoint:eXphQV7F0W7bq6YL:latest:3:852',
                graphId: 'eXphQV7F0W7bq6YL',
                nodeUid: 'root:result',
            },
        ]);
    });

});
